### ISSUE TITLE
How to reach the Dashboard?

### ISSUE THREAD

**Issue by Gill-Bates** [jedisct1/encrypted-dns-server#14]
Hi There,

how can I access the Dashboard?

**Comment by jedisct1** [comment]
The server can act as a Prometheus provider, by uncommenting the relevant section:

```toml
[metrics]
type = "prometheus"
listen_addr = "0.0.0.0:9100"
path = "/metrics"
```

In this configuration, the endpoint will be reachable at `http://...:9100/metrics`.

But this is not a dashboard. These are metrics that can be consumed by [Prometheus](https://prometheus.io/), that will store and index them. Then, you can plot them using the Prometheus web interface or another standard tool such as [Grafana](https://grafana.com/).
